version: '3.9'

services:
  message-service:
    build:
      context: ./php
      dockerfile: php-fpm.dockerfile
    volumes:
      - ./service:/var/www
    networks:
      - application-network
    container_name: message-service

  web-nginx:
    image: nginx:1.25.3-bookworm
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - application-network 
    ports:
      - "8080:80"
    links:
      - message-service
    depends_on: 
      - message-service

networks:
  application-network:
