version: '3.9'

services:
  message-service:
    build:
      context: ./php
      dockerfile: php-fpm.dockerfile
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: ChangeThis!
      MONGODB_HOST: mongodb://mongodb
      CONFIG_FILE: SystemConfig
    volumes:
      - ./service:/var/www/html
    networks:
      - simple-message-network
    links:
      - mongodb
    depends_on:
      - mongodb

  web-nginx:
    image: nginx:1.25.3-bookworm
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - simple-message-network 
    ports:
      - "8080:80"
    links:
      - message-service
    depends_on: 
      - message-service

  mongodb:
    image: mongo:7.0.5-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ChangeThis!
    networks:
      - simple-message-network

networks:
  simple-message-network:
